### ISSUE TITLE
Using Orion to Detect Anomaly in Personal Dataset

### ISSUE THREAD

**Issue by jgubner** [sintel-dev/Orion#227]
* Orion version:
* Python version: 3.7.3
* Operating System: macOS 11.2.3

### Description

I am trying to detect an anomalous feature in my personal dataset [BOX1_TEMP.csv](https://github.com/signals-dev/Orion/files/6421677/BOX1_TEMP.csv). I know that there is about a month's worth of data that is anomalous (in the 100s rather than the 20s). Can Orion detect this and give me the range of time where the data was anomalous? I have no idea if I am using the right primitive or pipeline. The data is not evenly spaced over time. I am also getting some errors about an index being out of bounds.

#### Inputs

```
filename = "BOX1_TEMP.csv"
from orion.data import load_signal

data = load_signal(filename)

from orion.analysis import analyze

hyperparameters = {
    "mlprimitives.custom.timeseries_preprocessing.rolling_window_sequences#1":{
        'index':9518
    },
    'keras.Sequential.LSTMTimeSeriesRegressor#1': {
        'epochs': 5,
        'verbose': True
    }
}

pipeline = 'lstm_dynamic_threshold'

anomalies = analyze(pipeline, data, hyperparams=hyperparameters)
anomalies
```
#### Outputs
```
Using TensorFlow backend.
ERROR:mlblocks.mlpipeline:Exception caught fitting MLBlock keras.Sequential.LSTMTimeSeriesRegressor#1
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.7/site-packages/mlblocks/mlpipeline.py", line 549, in _fit_block
    block.fit(**fit_args)
  File "/Applications/anaconda3/lib/python3.7/site-packages/mlblocks/mlblock.py", line 302, in fit
    getattr(self.instance, self.fit_method)(**fit_kwargs)
  File "/Applications/anaconda3/lib/python3.7/site-packages/mlprimitives/adapters/keras.py", line 98, in fit
    self._augment_hyperparameters(X, kwargs)
  File "/Applications/anaconda3/lib/python3.7/site-packages/mlprimitives/adapters/keras.py", line 89, in _augment_hyperparameters
    shape = np.asarray(X)[0].shape
IndexError: index 0 is out of bounds for axis 0 with size 0
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-12-68bd1be1d045> in <module>
     13 pipeline = 'lstm_dynamic_threshold'
     14 
---> 15 anomalies = analyze(pipeline, data, hyperparams=hyperparameters)
     16 anomalies

/Applications/anaconda3/lib/python3.7/site-packages/orion/analysis.py in analyze(pipeline, train, test, hyperparams)
     46         pipeline = _load_pipeline(pipeline, hyperparams)
     47 
---> 48     events = _run_pipeline(pipeline, train, test)
     49 
     50     return _build_events_df(events)

/Applications/anaconda3/lib/python3.7/site-packages/orion/analysis.py in _run_pipeline(pipeline, train, test)
     22 def _run_pipeline(pipeline, train, test):
     23     LOGGER.debug("Fitting the pipeline")
---> 24     pipeline.fit(train)
     25 
     26     LOGGER.debug("Finding events")

/Applications/anaconda3/lib/python3.7/site-packages/mlblocks/mlpipeline.py in fit(self, X, y, output_, start_, **kwargs)
    647                     continue
    648 
--> 649             self._fit_block(block, block_name, context)
    650 
    651             if (block_name != self._last_block_name) or (block_name in output_blocks):

/Applications/anaconda3/lib/python3.7/site-packages/mlblocks/mlpipeline.py in _fit_block(self, block, block_name, context)
    547         try:
    548             fit_args = self._get_block_args(block_name, block.fit_args, context)
--> 549             block.fit(**fit_args)
    550         except Exception:
    551             if self.verbose:

/Applications/anaconda3/lib/python3.7/site-packages/mlblocks/mlblock.py in fit(self, **kwargs)
    300             fit_kwargs.update(kwargs)
    301             fit_kwargs = self._get_method_kwargs(fit_kwargs, self.fit_args)
--> 302             getattr(self.instance, self.fit_method)(**fit_kwargs)
    303 
    304     def produce(self, **kwargs):

/Applications/anaconda3/lib/python3.7/site-packages/mlprimitives/adapters/keras.py in fit(self, X, y, **kwargs)
     96 
     97     def fit(self, X, y, **kwargs):
---> 98         self._augment_hyperparameters(X, kwargs)
     99         self.model = self._build_model(**kwargs)
    100 

/Applications/anaconda3/lib/python3.7/site-packages/mlprimitives/adapters/keras.py in _augment_hyperparameters(self, X, kwargs)
     87 
     88     def _augment_hyperparameters(self, X, kwargs):
---> 89         shape = np.asarray(X)[0].shape
     90         length = shape[0]
     91         self._setdefault(kwargs, 'input_shape', shape)

IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by sarahmish** [comment]
Hi @jgubner, thanks for opening this issue! There are some elements needed to be taken care of, I will go through this step by step

### Raw Data
You can definitely use your own data in Orion, we only require it to be in a `['timestamp', 'value']` format (which it is) but additionally, the `timestamp` column **needs** to be of integer type, preferably a unix timestamp.

### Aggregation Levels
The first step in all our pipelines is to define the aggregation level you want, this makes the signal equi-spaced. For this primitive, you need to set the `interval` hyperparameter accordingly. For example, if your data has a frequency of 5 minutes then `interval=300` would be most appropriate since we are dealing with second intervals.
```python3
hyperparameters = {
    "mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1": {
        "interval": 300
    }
}
```
I understand your data has inconsistent spacing, it would be best if you have an estimate of what aggregation interval would work best because the remaining pipeline is under the assumption that each value and another are equally spaced.

### Rolling Window Sequences
I'm a little bit confused here as to why you are setting `index` to a single value. The `rolling_window_sequence` primitive requires two inputs: `X (ndarray)`, and `index (ndarray)` which are one-to-one corresponding. This is something you do **NOT** need to modify because it is implicitly taken care of within the pipeline. More on the primitive documentation [here](https://signals-dev.github.io/Orion/user_guides/primitives_pipelines/primitives/rolling_window_sequences.html). 
If you wish to change the window size of the primitive, say `window_size=100` then you change that particular hyperparameter. 
```python3
hyperparameters = {
    "mlprimitives.custom.timeseries_preprocessing. rolling_window_sequences#1": {
        "window_size": 100
    }
}
```

### Putting a Pipeline Together
Per your example, you have selected the `lstm_dynamic_threshold` pipeline, which is a prediction based pipeline. After you have transformed your data into a format usable by Orion, we can put everything together
```python3
from orion import Orion

hyperparameters = {
    "mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1": {
        "interval": 300
    },
    "mlprimitives.custom.timeseries_preprocessing. rolling_window_sequences#1": {
        "window_size": 100
    },
    "keras.Sequential.LSTMTimeSeriesRegressor#1": {
        "epochs": 5,
        "verbose": True
    }
}

orion = Orion(
    pipeline='lstm_dynamic_threshold',
    hyperparameters=hyperparameters
)

orion.fit(data)
```

Let me know if this makes sense and if you have any further questions

**Comment by jgubner** [comment]
Hi @sarahmish, thank you for the information.

I tried what you suggested, but I am now getting a key error:

```
KeyError                                  Traceback (most recent call last)
<ipython-input-30-57be5ca3b78f> in <module>
     14 orion = Orion(
     15     pipeline='lstm_dynamic_threshold',
---> 16     hyperparameters=hyperparameters
     17 )
     18 

/Applications/anaconda3/lib/python3.7/site-packages/orion/core.py in __init__(self, pipeline, hyperparameters)
     62         self._pipeline = pipeline or self.DEFAULT_PIPELINE
     63         self._hyperparameters = hyperparameters
---> 64         self._mlpipeline = self._get_mlpipeline()
     65         self._fitted = False
     66 

/Applications/anaconda3/lib/python3.7/site-packages/orion/core.py in _get_mlpipeline(self)
     54         mlpipeline = MLPipeline(pipeline)
     55         if self._hyperparameters:
---> 56             mlpipeline.set_hyperparameters(self._hyperparameters)
     57 
     58         return mlpipeline

/Applications/anaconda3/lib/python3.7/site-packages/mlblocks/mlpipeline.py in set_hyperparameters(self, hyperparameters)
    477         hyperparameters = self._sanitize(hyperparameters)
    478         for block_name, block_hyperparams in hyperparameters.items():
--> 479             self.blocks[block_name].set_hyperparameters(block_hyperparams)
    480 
    481     def _get_block_args(self, block_name, block_args, context):

KeyError: 'mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1'

```

**Comment by sarahmish** [comment]
@jgubner that could be a possibility of two things:
1. there were some unnecessary blanks in the snippets above. I corrected them, please try to run it again.
2. if you are still facing the same issue, may I know how you installed Orion?
