### ISSUE TITLE
Anomaly detection changes with length of the same input signal

### ISSUE THREAD

**Issue by yaseryacoob** [sintel-dev/Orion#288]
After training an LSTM model on a dataset, In testing on different lengths cuts of the one signal. So if the signal is 5000 long, I score different lengths from the beginning, let's say, first 800, 1200, 1600, 2600 and then 5000. The number of the anomaly detections, locations and severity vary. So for example,

1.  I got detections at the same location for 800 and 1200 let's say at 550-6000, but the severity values is is different.
2.  Then this anomaly location(550-600)  disappears when I move to testing on 0-1600 and 0-2000.
I tested both LSTM with dynamic threshold and LSTM Auto encoder.

While the dynamic thresholding maybe the cause of this for LSTM_dynamic thresholding, I am not sure I get why LSTM_auto_encoder should be affected. Also, in general, one would expect "anomaly detection" to be no sensitive to signal length (beyond window size).

Can you please explain or suggest which parameters may be needed to stabilize the performance?

thanks.

**Comment by sarahmish** [comment]
Hi @yaseryacoob, thank you for your question!

Most pipelines are actually sensitive to the length of the time series, and I will explain why. Let's take `lstm_autoencoder` as an example, in the `find_anomalies` primitive, we set a `window_size_portion` and `window_step_size_portion` that are based on the size of the time series. This is to reduce the number of manual settings needed from the user side.

https://github.com/sintel-dev/Orion/blob/6f22205e2d5349681cadbc3ea130ab4d397f6f9a/orion/pipelines/verified/lstm_autoencoder/lstm_autoencoder.json#L35-L37

To make it more "static" in a sense, you can remove the aforementioned hyperparameters and make them absolute as follows (this is an example, you need to find which parameters work for your case):
```
"orion.primitives.timeseries_anomalies.find_anomalies#1": { 
    "window_size": 200, 
    "window_step_size": 50,
} 
```

In addition, to ensure reproducibility, you can try to seed `keras` in your code by using `tensorflow` seeding functions.


I hope this answers your question! Let me know if you have any more :)

**Comment by yaseryacoob** [comment]
Thanks @sarahmish I made the changes and the detections are relatively stable. If I may followup with two questions:

1. How do I get the complete anomaly scores for a sequence? (i.e. N scores for N long sequence)
2. I tried to install with a GPU, and ran into some incompatibilities, which after a while forced me to give up. If you have a GPU installation, can you please specify the environment so I replicate it? (via a requirements or conda env).

Thanks.

**Comment by sarahmish** [comment]
Great!

1. If you want to obtain the anomaly scores which are defined by the "error" curve, you can specify that you would like additional outputs to visualize by include this in your pipeline json. Let's continue with the `lstm_autoencoder` example, we can have the following:
```
"outputs": {
    "default": [
        {
            "name": "events",
            "variable": "orion.primitives.timeseries_anomalies.find_anomalies#1.y"
        }
    ],
    "visualization": [
        {
            "name": "anomaly_scores",
            "variable": "orion.primitives.timeseries_errors.reconstruction_errors#1.errors"
        }
    ]
}
```

Then when running Orion, you can specify `visualization=True` to acquire that output

```python3
anomalies, viz = orion.detect(signal, visualization=True)
```
where `viz` is now a dictionary with a `anomaly_scores` key

2. To run on GPU, you can use `lstm_autoencoder_gpu` [version](https://github.com/sintel-dev/Orion/blob/master/orion/pipelines/verified/lstm_autoencoder/lstm_autoencoder_gpu.json) of the pipeline. The exact configuration of `conda` and CUDA depends on your system. Here are some resources to guide you through the setup https://www.tensorflow.org/install/gpu and https://www.tensorflow.org/install/source#gpu. Also keep in mind that Orion is currently using tensorflow 1. My personal setup is to have `tensorflow==1.14` and `tensorflow-gpu==1.14` with CUDA 10.0

**Comment by yaseryacoob** [comment]
I will check on 1 early tomorrow. 

For the GPU, I used tensorflow==1.14 and tensorflow-gpu==1.14 with CUDA 10.0  all in a conda environment. It turned out to cause conflicts with pandas versions (at times numpy/scipy versions). The final error was below (pandas==0.24.2, which is the same I have for the CPU version!), when I gave up (after 2 rounds of trying over). If you can run a pip list and send it to me, or a conda installation sequence if this is what you use, I would much prefer to use the GPU. I know sometimes the installation sequence of packages can be a make or break.

```
(orionGPU) yaser@yaserubuntu:/media/ydrive/time_series/Orion$ python yy.py
/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/sklearn/utils/validation.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LARGE_SPARSE_SUPPORTED = LooseVersion(scipy_version) >= '0.14.0'
Using TensorFlow backend.
Exception caught fitting MLBlock keras.Sequential.LSTMTimeSeriesRegressor#1
Traceback (most recent call last):
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/mlblocks/mlpipeline.py", line 549, in _fit_block
    block.fit(**fit_args)
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/mlblocks/mlblock.py", line 302, in fit
    getattr(self.instance, self.fit_method)(**fit_kwargs)
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/mlprimitives/adapters/keras.py", line 99, in fit
    self.model = self._build_model(**kwargs)
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/mlprimitives/adapters/keras.py", line 54, in _build_model
    model.add(built_layer)
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/keras/engine/sequential.py", line 166, in add
    layer(x)
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/keras/layers/recurrent.py", line 541, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/keras/layers/cudnn_recurrent.py", line 425, in build
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/__init__.py", line 41, in <module>
    from tensorflow.contrib import distributions
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/distributions/__init__.py", line 44, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/distributions/python/ops/estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/__init__.py", line 93, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/python/__init__.py", line 28, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 302, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 34, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 36, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 52, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 26, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 33, in <module>
    import dask.dataframe as dd
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from . import backends, dispatch, rolling
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/dask/dataframe/backends.py", line 23, in <module>
    from .core import DataFrame, Index, Scalar, Series, _Frame
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/dask/dataframe/core.py", line 50, in <module>
    from . import methods
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/dask/dataframe/methods.py", line 21, in <module>
    from .utils import is_dataframe_like, is_index_like, is_series_like
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/dask/dataframe/utils.py", line 25, in <module>
    from . import _dtypes  # noqa: F401 register pandas extension types
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/dask/dataframe/_dtypes.py", line 16, in <module>
    @make_array_nonempty.register(pd.StringDtype)
AttributeError: module 'pandas' has no attribute 'StringDtype'
Traceback (most recent call last):
  File "yy.py", line 69, in <module>
    orion.fit(train_data)
  File "/media/ydrive/time_series/Orion/orion/core.py", line 86, in fit
    self._mlpipeline.fit(data, **kwargs)
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/mlblocks/mlpipeline.py", line 649, in fit
    self._fit_block(block, block_name, context)
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/mlblocks/mlpipeline.py", line 549, in _fit_block
    block.fit(**fit_args)
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/mlblocks/mlblock.py", line 302, in fit
    getattr(self.instance, self.fit_method)(**fit_kwargs)
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/mlprimitives/adapters/keras.py", line 99, in fit
    self.model = self._build_model(**kwargs)
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/mlprimitives/adapters/keras.py", line 54, in _build_model
    model.add(built_layer)
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/keras/engine/sequential.py", line 166, in add
    layer(x)
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/keras/layers/recurrent.py", line 541, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/keras/layers/cudnn_recurrent.py", line 425, in build
    from tensorflow.contrib.cudnn_rnn.python.ops import cudnn_rnn_ops
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/__init__.py", line 41, in <module>
    from tensorflow.contrib import distributions
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/distributions/__init__.py", line 44, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/distributions/python/ops/estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/__init__.py", line 93, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/python/__init__.py", line 28, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 302, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 34, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 36, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 52, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 26, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 33, in <module>
    import dask.dataframe as dd
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from . import backends, dispatch, rolling
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/dask/dataframe/backends.py", line 23, in <module>
    from .core import DataFrame, Index, Scalar, Series, _Frame
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/dask/dataframe/core.py", line 50, in <module>
    from . import methods
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/dask/dataframe/methods.py", line 21, in <module>
    from .utils import is_dataframe_like, is_index_like, is_series_like
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/dask/dataframe/utils.py", line 25, in <module>
    from . import _dtypes  # noqa: F401 register pandas extension types
  File "/home/yaser/miniconda3/envs/orionGPU/lib/python3.7/site-packages/dask/dataframe/_dtypes.py", line 16, in <module>
    @make_array_nonempty.register(pd.StringDtype)
AttributeError: module 'pandas' has no attribute 'StringDtype'
(orionGPU) yaser@yaserubuntu:/media/ydrive/time_series/Orion$ 

```

Thanks

**Comment by sarahmish** [comment]
@yaseryacoob this is my pip freeze for the packages you are having troubles with

```
tensorflow==1.14.0
tensorflow-estimator==1.14.0
tensorflow-gpu==1.14.0
numpy==1.16.6
pandas==0.24.2
scipy==1.5.2
dask==2.23.0
```

**Comment by yaseryacoob** [comment]
My pip freeze for GPU is far more extensive, see below, and also the CPU version is extensive. Both are conda environments.
The error is the same in the GPU version, as I reported yesterday.
Note that the CPU uses tensorflow 1.15.0 while the GPU is tensorflow 1.14.0

It would be great if there are clean instructions for GPU installtaion in conda or virtual environment.

thanks


-------------GPU freeze
(orionGPU3) yaser@yaserubuntu:/media/ydrive/time_series/Orion$ pip freeze
absl-py @ file:///home/conda/feedstock_root/build_artifacts/absl-py_1637088766493/work
aiobotocore==2.2.0
aiohttp==3.8.1
aioitertools==0.10.0
aiosignal==1.2.0
astor @ file:///home/conda/feedstock_root/build_artifacts/astor_1593610464257/work
async-timeout==4.0.2
asynctest==0.13.0
attrs==21.4.0
azure-cognitiveservices-anomalydetector==0.3.0
azure-common==1.1.28
botocore==1.24.21
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
certifi==2021.10.8
charset-normalizer==2.0.12
click==8.1.2
cloudpickle==2.0.0
cycler==0.11.0
dask==2022.2.0
distributed==2022.2.0
docutils==0.15.2
featuretools==0.11.0
fonttools==4.33.0
frozenlist==1.3.0
fsspec==2022.3.0
future==0.18.2
gast @ file:///home/conda/feedstock_root/build_artifacts/gast_1636964356021/work
google-pasta==0.2.0
graphviz==0.20
grpcio @ file:///home/conda/feedstock_root/build_artifacts/grpcio_1648220671878/work
h5py==2.10.0
HeapDict==1.0.1
idna==3.3
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1648728291958/work
iso639==0.1.4
isodate==0.6.1
Jinja2==3.1.1
jmespath==1.0.0
joblib==1.1.0
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing @ file:///home/conda/feedstock_root/build_artifacts/keras-preprocessing_1610713559828/work
kiwisolver==1.4.2
langdetect==1.0.9
lightfm==1.16
llvmlite==0.34.0
locket==1.0.0
Markdown @ file:///home/conda/feedstock_root/build_artifacts/markdown_1637220118004/work
MarkupSafe==2.1.1
matplotlib==3.4.3
mlblocks==0.3.4
mlprimitives==0.2.5
mongoengine==0.24.1
msgpack==1.0.3
msrest==0.6.21
multidict==6.0.2
networkx==2.6.3
nltk==3.7
numba==0.51.2
numpy==1.16.6
oauthlib==3.2.0
opencv-python==4.5.5.64
orion-ml==0.2.1
packaging==21.3
pandas==0.24.2
partd==1.2.0
patsy==0.5.2
Pillow==9.1.0
protobuf==3.20.0rc2
psutil==5.9.0
pymongo==3.12.3
pyparsing==3.0.8
python-dateutil==2.8.2
python-louvain==0.13
pyts==0.10.0
pytz==2022.1
PyWavelets==1.1.1
PyYAML==6.0
regex==2022.3.15
requests==2.27.1
requests-oauthlib==1.3.1
s3fs==0.4.2
scikit-image==0.14.5
scikit-learn==0.20.4
scipy==1.5.2
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
sklearn==0.0
smart-open==5.2.1
sortedcontainers==2.4.0
statsmodels==0.12.2
tabulate==0.8.9
tblib==1.7.0
tensorboard==1.14.0
tensorflow @ file:///home/conda/feedstock_root/build_artifacts/tensorflow_1594833314895/work/tensorflow_pkg/tensorflow-1.14.0-cp37-cp37m-linux_x86_64.whl
tensorflow-estimator==1.14.0
tensorflow-gpu==1.14.0
termcolor==1.1.0
threadpoolctl==3.1.0
toolz==0.11.2
tornado==6.1
tqdm==4.64.0
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1650370875435/work
urllib3==1.26.9
Werkzeug @ file:///home/conda/feedstock_root/build_artifacts/werkzeug_1648847766614/work
wrapt @ file:///home/conda/feedstock_root/build_artifacts/wrapt_1649093996910/work
xgboost==0.90
XlsxWriter==3.0.3
yarl==1.7.2
zict==2.1.0
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1649012893348/work
(orionGPU3) yaser@yaserubuntu:/media/ydrive/time_series/Orion$
--------------------------------------------------------------------------------------------------------------------------
(orion) yaser@yaserubuntu:/media/ydrive/time_series/Orion$ pip freeze
absl-py==1.0.0
astor==0.8.1
azure-cognitiveservices-anomalydetector==0.3.0
azure-common==1.1.28
botocore==1.24.21
certifi==2021.10.8
charset-normalizer==2.0.12
click==8.0.4
cloudpickle==2.0.0
cycler==0.11.0
dask==2022.2.0
distributed==2022.2.0
docutils==0.15.2
featuretools==0.11.0
fsspec==2022.2.0
future==0.18.2
gast==0.2.2
google-pasta==0.2.0
grpcio==1.44.0
h5py==2.10.0
HeapDict==1.0.1
idna==3.3
importlib-metadata==4.11.3
iso639==0.1.4
isodate==0.6.1
Jinja2==3.0.3
jmespath==1.0.0
joblib==1.1.0
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.4.0
langdetect==1.0.9
lightfm==1.16
llvmlite==0.34.0
locket==0.2.1
Markdown==3.3.6
MarkupSafe==2.1.1
matplotlib==3.4.3
mlblocks==0.3.4
mlprimitives==0.2.5
mongoengine==0.24.0
msgpack==1.0.3
msrest==0.6.21
networkx==2.6.3
nltk==3.7
numba==0.51.2
numpy==1.16.6
oauthlib==3.2.0
opencv-python==4.5.5.64
opt-einsum==3.3.0
orion-ml==0.2.1
packaging==21.3
pandas==0.24.2
partd==1.2.0
patsy==0.5.2
Pillow==9.0.1
protobuf==3.19.4
psutil==5.9.0
pymongo==3.12.3
pyparsing==3.0.7
python-dateutil==2.8.2
python-louvain==0.13
pyts==0.10.0
pytz==2021.3
PyWavelets==1.1.1
PyYAML==6.0
regex==2022.3.15
requests==2.27.1
requests-oauthlib==1.3.1
s3fs==0.4.2
scikit-image==0.14.5
scikit-learn==0.20.4
scipy==1.7.3
six==1.16.0
smart-open==5.2.1
sortedcontainers==2.4.0
statsmodels==0.12.2
tabulate==0.8.9
tblib==1.7.0
tensorboard==1.15.0
tensorflow==1.15.5
tensorflow-estimator==1.15.1
termcolor==1.1.0
toolz==0.11.2
tornado==6.1
tqdm==4.63.0
typing_extensions==4.1.1
urllib3==1.26.9
Werkzeug==2.0.3
wrapt==1.14.0
xgboost==0.90
XlsxWriter==3.0.3
zict==2.1.0
zipp==3.7.0
(orion) yaser@yaserubuntu:/media/ydrive/time_series/Orion$

**Comment by sarahmish** [comment]
Thanks @yaseryacoob, I only posted the pip freeze of relevant packages, I was able to install `pandas`, `numpy`, and `scipy` of the above versions without conflict. The only package I see that has a different version is `dask`.

**Comment by yaseryacoob** [comment]
Thanks @sarahmish   I ended up fixing the installation, i corrected the dask before, but more importantly is that both must be 

dask==2.23.0
distributed==2.23.0
