### ISSUE TITLE
InvalidParameterError: The 'feature_range' parameter of MinMaxScaler must be an instance of 'tuple'. Got [-1, 1] instead.

### ISSUE THREAD

**Issue by MahmoudWali** [sintel-dev/Orion#371]
* Orion version: v0.4.0 - 2022-11-10
* Python version: 3.8.15
* Operating System: Windows 10

### Description

Hello,

I tried to run the demo example but I have error when I execute orion.fit(train_data)

InvalidParameterError: The 'feature_range' parameter of MinMaxScaler must be an instance of 'tuple'. Got [-1, 1] instead.

This is the full output:

D:\anaconda3\envs\orionNew\lib\site-packages\sklearn\impute\_base.py:381: FutureWarning: The 'verbose' parameter was deprecated in version 1.1 and will be removed in 1.3. A warning will always be raised upon the removal of empty columns in the future version.
  warnings.warn(
Exception caught fitting MLBlock sklearn.preprocessing.MinMaxScaler#1
Traceback (most recent call last):
  File "D:\anaconda3\envs\orionNew\lib\site-packages\mlblocks\mlpipeline.py", line 644, in _fit_block
    block.fit(**fit_args)
  File "D:\anaconda3\envs\orionNew\lib\site-packages\mlblocks\mlblock.py", line 311, in fit
    getattr(self.instance, self.fit_method)(**fit_kwargs)
  File "D:\anaconda3\envs\orionNew\lib\site-packages\sklearn\preprocessing\_data.py", line 427, in fit
    return self.partial_fit(X, y)
  File "D:\anaconda3\envs\orionNew\lib\site-packages\sklearn\preprocessing\_data.py", line 450, in partial_fit
    self._validate_params()
  File "D:\anaconda3\envs\orionNew\lib\site-packages\sklearn\base.py", line 570, in _validate_params
    validate_parameter_constraints(
  File "D:\anaconda3\envs\orionNew\lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'feature_range' parameter of MinMaxScaler must be an instance of 'tuple'. Got [-1, 1] instead.
Traceback (most recent call last):

  File "C:\Users\engma\AppData\Local\Temp\ipykernel_15280\338572060.py", line 1, in <module>
    orion.fit(train_data)

  File "D:\anaconda3\envs\orionNew\lib\site-packages\orion\core.py", line 111, in fit
    self._mlpipeline.fit(data, **kwargs)

  File "D:\anaconda3\envs\orionNew\lib\site-packages\mlblocks\mlpipeline.py", line 802, in fit
    self._fit_block(block, block_name, context, debug_info)

  File "D:\anaconda3\envs\orionNew\lib\site-packages\mlblocks\mlpipeline.py", line 644, in _fit_block
    block.fit(**fit_args)

  File "D:\anaconda3\envs\orionNew\lib\site-packages\mlblocks\mlblock.py", line 311, in fit
    getattr(self.instance, self.fit_method)(**fit_kwargs)

  File "D:\anaconda3\envs\orionNew\lib\site-packages\sklearn\preprocessing\_data.py", line 427, in fit
    return self.partial_fit(X, y)

  File "D:\anaconda3\envs\orionNew\lib\site-packages\sklearn\preprocessing\_data.py", line 450, in partial_fit
    self._validate_params()

  File "D:\anaconda3\envs\orionNew\lib\site-packages\sklearn\base.py", line 570, in _validate_params
    validate_parameter_constraints(

  File "D:\anaconda3\envs\orionNew\lib\site-packages\sklearn\utils\_param_validation.py", line 97, in validate_parameter_constraints
    raise InvalidParameterError(

InvalidParameterError: The 'feature_range' parameter of MinMaxScaler must be an instance of 'tuple'. Got [-1, 1] instead.

Any help how to fix this error which is related to sklearn. 
Thank you

**Comment by sarahmish** [comment]
Hi @MahmoudWali, thank you for opening this issue!

Can you try downgrading sklearn?
```
pip uninstall scikit-learn
pip install "scikit-learn>=0.22,<1.2"
```

Let me know if you are still facing issues

**Comment by MahmoudWali** [comment]
Hi @sarahmish 
Yes it works fine.
Many thanks!
