### ISSUE TITLE
Cannot `.fit_detect()` using any pipeline except for tadgan.json (using Colab)

### ISSUE THREAD

**Issue by nunobv** [sintel-dev/Orion#409]
* Orion version: 0.4.1
* Python version: 3.8.10
* Operating System: Running on Colab

### Description
Hi! First of all let me praise the work you've been doing. Really appreciate it!

I was trying to play with the [Tulog ](https://github.com/sintel-dev/Orion/blob/master/tutorials/tulog/Tulog.ipynb) using Colab. Everything went perfectly fine with the predefined tutorial using `tadgan`.
However, I wanted to quickly compare the results of the `tadgan` pipeline with some of the other **verified** pipelines available.

When I try to call some of the other available pipelines, I get an error during the `.fit_detect()` stage. I'll share my bit of code and the corresponding error for the `LSTM_Autoencoder`, `ARIMA` and `AER` pipelines, as each error is different.

Am I doing something wrong (probably)? Am I missing something (also probable)?
Thanks in advance.

### What I Did

```
from orion import Orion
from orion.data import load_signal, load_anomalies
from orion.evaluation.contextual import contextual_accuracy, contextual_f1_score, contextual_precision

signal = 'nyc_taxi'

# load signal
df = load_signal(signal)

# load ground truth anomalies
ground_truth = load_anomalies(signal)
```

#### LSTM AUTOENCODER
```
hyperparameters_lstm = {
    "mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1": {
            "interval": 1800
    },
    'sklearn.preprocessing.MinMaxScaler#1': {
        'feature_range': (-1, 1)
    }
}

orion_lstm = Orion(
    '/content/Orion/orion/pipelines/verified/lstm_autoencoder/lstm_autoencoder.json',
    hyperparameters_lstm
)

anomalies_lstm = orion_lstm.fit_detect(df)
```

```
ERROR:mlblocks.mlpipeline:Exception caught fitting MLBlock keras.Sequential.LSTMSeq2Seq#1
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/mlblocks/mlpipeline.py", line 644, in _fit_block
    block.fit(**fit_args)
  File "/usr/local/lib/python3.8/dist-packages/mlblocks/mlblock.py", line 311, in fit
    getattr(self.instance, self.fit_method)(**fit_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mlprimitives/adapters/keras.py", line 106, in fit
    self.model = self._build_model(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mlprimitives/adapters/keras.py", line 53, in _build_model
    built_layer = build_layer(layer, hyperparameters)
  File "/usr/local/lib/python3.8/dist-packages/mlprimitives/adapters/keras.py", line 17, in build_layer
    if issubclass(layer_class, keras.layers.wrappers.Wrapper):
AttributeError: module 'keras.layers' has no attribute 'wrappers'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-42-b43cf2bdb506>](https://localhost:8080/#) in <cell line: 22>()
     20 ]
     21 
---> 22 anomalies_lstm = orion_lstm.fit_detect(df)

7 frames
[/usr/local/lib/python3.8/dist-packages/orion/core.py](https://localhost:8080/#) in fit_detect(self, data, visualization, **kwargs)
    207             self._mlpipeline = self._get_mlpipeline()
    208 
--> 209         result = self._detect(self._mlpipeline.fit, data, visualization, **kwargs)
    210         self._fitted = True
    211 

[/usr/local/lib/python3.8/dist-packages/orion/core.py](https://localhost:8080/#) in _detect(self, method, data, visualization, **kwargs)
    136             outputs_spec = 'default'
    137 
--> 138         outputs = method(data, output_=outputs_spec, **kwargs)
    139 
    140         if visualization:

[/usr/local/lib/python3.8/dist-packages/mlblocks/mlpipeline.py](https://localhost:8080/#) in fit(self, X, y, output_, start_, debug, **kwargs)
    800                     continue
    801 
--> 802             self._fit_block(block, block_name, context, debug_info)
    803 
    804             if fit_pending or output_blocks:

[/usr/local/lib/python3.8/dist-packages/mlblocks/mlpipeline.py](https://localhost:8080/#) in _fit_block(self, block, block_name, context, debug_info)
    642             memory_before = process.memory_info().rss
    643             start = datetime.utcnow()
--> 644             block.fit(**fit_args)
    645             elapsed = datetime.utcnow() - start
    646             memory_after = process.memory_info().rss

[/usr/local/lib/python3.8/dist-packages/mlblocks/mlblock.py](https://localhost:8080/#) in fit(self, **kwargs)
    309             fit_kwargs.update(kwargs)
    310             fit_kwargs = self._get_method_kwargs(fit_kwargs, self.fit_args)
--> 311             getattr(self.instance, self.fit_method)(**fit_kwargs)
    312 
    313     def produce(self, **kwargs):

[/usr/local/lib/python3.8/dist-packages/mlprimitives/adapters/keras.py](https://localhost:8080/#) in fit(self, X, y, **kwargs)
    104             self._augment_hyperparameters(X, 'input', kwargs)
    105             self._augment_hyperparameters(y, 'target', kwargs)
--> 106             self.model = self._build_model(**kwargs)
    107 
    108         if self.classification:

[/usr/local/lib/python3.8/dist-packages/mlprimitives/adapters/keras.py](https://localhost:8080/#) in _build_model(self, **kwargs)
     51 
     52         for layer in self.layers:
---> 53             built_layer = build_layer(layer, hyperparameters)
     54             model.add(built_layer)
     55 

[/usr/local/lib/python3.8/dist-packages/mlprimitives/adapters/keras.py](https://localhost:8080/#) in build_layer(layer, hyperparameters)
     15     layer_class = import_object(layer['class'])
     16     layer_kwargs = layer['parameters'].copy()
---> 17     if issubclass(layer_class, keras.layers.wrappers.Wrapper):
     18         layer_kwargs['layer'] = build_layer(layer_kwargs['layer'], hyperparameters)
     19     for key, value in layer_kwargs.items():

AttributeError: module 'keras.layers' has no attribute 'wrappers'
```

#### AER
```
hyperparameters_aer = {
    "mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1": {
            "interval": 1800
    },
    'sklearn.preprocessing.MinMaxScaler#1': {
        'feature_range': (-1, 1)
    }
}

orion_aer = Orion(
    '/content/Orion/orion/pipelines/verified/aer/aer.json',
    hyperparameters_aer
)

anomalies_aer = orion_aer.fit_detect(df)
```
```
ERROR:mlblocks.mlpipeline:Exception caught fitting MLBlock sklearn.preprocessing.MinMaxScaler#1
...
InvalidParameterError: The 'feature_range' parameter of MinMaxScaler must be an instance of 'tuple'. Got [-1, 1] instead.
```

#### ARIMA

```
hyperparameters_arima = {
    "mlprimitives.custom.timeseries_preprocessing.time_segments_aggregate#1": {
            "interval": 1800
    },
    'sklearn.preprocessing.MinMaxScaler#1': {
        'feature_range': (-1, 1)
    }
}

orion_arima = Orion(
    '/content/Orion/orion/pipelines/verified/arima/arima.json',
    hyperparameters_arima
)

anomalies_arima = orion_arima.fit_detect(df)
```

```
NotImplementedError: 
statsmodels.tsa.arima_model.ARMA and statsmodels.tsa.arima_model.ARIMA have
been removed in favor of statsmodels.tsa.arima.model.ARIMA (note the .
between arima and model) and statsmodels.tsa.SARIMAX.

statsmodels.tsa.arima.model.ARIMA makes use of the statespace framework and
is both well tested and maintained. It also offers alternative specialized
parameter estimators.
```

**Comment by sarahmish** [comment]
Hi @nunobv, thank you for using Orion!

I appreciate your comments :)

I want to first emphasize that most of the issues you are seeing is because of google colab. If you were to experiment with Orion in a virtual environment on your machine, you will most likely have a seamless experience.

**LSTM DT**
the module `keras.layers.wrappers.Wrapper` in mlprimitives package needs to change to `tf.keras.layers.Wrapper`. If you downgrade Keras and tensorflow, this error would be solved.

**AER**
this is a bug and I opened an issue #412 to follow-up on this. Thanks for catching it!
downgrade to `scikit-learn<1.2` should fix it for now. 

**ARIMA**
this is also a version problem. you need to downgrade statsmodel.

All the issues above are because of version incompatibility with Orion. So going back and running the notebook on a virtual or conda environment should make things run better.
I am also working on adding python 3.9 to make the google colab more friendly with orion.

Thanks and let me know if you have any further questions!
