### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by erioe-m** [sintel-dev/Orion#456]
* Orion version: 0.5.1
* Python version: Python 3.8.2
* Operating System: MacBook Pro (13-inch, M1, 2020) ,macOS Big Sur 11.5.2 (20G95)

### Description

pip install orion-ml   An error occurred

Collecting orion-ml
  Obtaining dependency information for orion-ml from https://files.pythonhosted.org/packages/38/38/103c115f0ffc488e52f3df4bd50f3f143f4902a966875f54e0b7a4ef3638/orion_ml-0.5.1-py2.py3-none-any.whl.metadata
  Using cached orion_ml-0.5.1-py2.py3-none-any.whl.metadata (23 kB)
Collecting s3fs<0.5,>=0.2.2 (from orion-ml)
  Using cached s3fs-0.4.2-py3-none-any.whl (19 kB)
Collecting mlblocks<0.5,>=0.4.1 (from orion-ml)
  Using cached mlblocks-0.4.1-py2.py3-none-any.whl (25 kB)
Collecting ml-stars<0.2,>=0.1.1 (from orion-ml)
  Obtaining dependency information for ml-stars<0.2,>=0.1.1 from https://files.pythonhosted.org/packages/39/06/c97e2375fe65742303fd57c81c4fc4ff4942efc9724f4ba0c2298612d50f/ml_stars-0.1.2-py2.py3-none-any.whl.metadata
  Using cached ml_stars-0.1.2-py2.py3-none-any.whl.metadata (7.4 kB)
Collecting numpy<1.19,>=1.17.4 (from orion-ml)
  Using cached numpy-1.18.5.zip (5.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      warning: _philox.pyx:19:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: /private/var/folders/v8/gk_4t45j1nsdpk0rkg56hbgw0000gn/T/pip-install-09jru_i9/numpy_a61a53fde6b74227a9aa0258630ff913/numpy/__init__.pxd:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  self.rng_state.ctr.v[i] = counter[i]
      
              self._reset_state_variables()
      
              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &philox_uint64
                                         ^
      ------------------------------------------------------------
      
      _philox.pyx:195:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'uint64_t (void *) except? -1 nogil'.
      /private/var/folders/v8/gk_4t45j1nsdpk0rkg56hbgw0000gn/T/pip-install-09jru_i9/numpy_a61a53fde6b74227a9aa0258630ff913/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      /private/var/folders/v8/gk_4t45j1nsdpk0rkg56hbgw0000gn/T/pip-install-09jru_i9/numpy_a61a53fde6b74227a9aa0258630ff913/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Traceback (most recent call last):
        File "/private/var/folders/v8/gk_4t45j1nsdpk0rkg56hbgw0000gn/T/pip-install-09jru_i9/numpy_a61a53fde6b74227a9aa0258630ff913/tools/cythonize.py", line 238, in <module>
          main()
        File "/private/var/folders/v8/gk_4t45j1nsdpk0rkg56hbgw0000gn/T/pip-install-09jru_i9/numpy_a61a53fde6b74227a9aa0258630ff913/tools/cythonize.py", line 234, in main
          find_process_files(root_dir)
        File "/private/var/folders/v8/gk_4t45j1nsdpk0rkg56hbgw0000gn/T/pip-install-09jru_i9/numpy_a61a53fde6b74227a9aa0258630ff913/tools/cythonize.py", line 225, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/private/var/folders/v8/gk_4t45j1nsdpk0rkg56hbgw0000gn/T/pip-install-09jru_i9/numpy_a61a53fde6b74227a9aa0258630ff913/tools/cythonize.py", line 191, in process
          processor_function(fromfile, tofile)
        File "/private/var/folders/v8/gk_4t45j1nsdpk0rkg56hbgw0000gn/T/pip-install-09jru_i9/numpy_a61a53fde6b74227a9aa0258630ff913/tools/cythonize.py", line 80, in process_pyx
          subprocess.check_call(
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/erioe/PycharmProjects/cloud-ability-orion/venv/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_philox.c', '_philox.pyx']' returned non-zero exit status 1.
      Running from numpy source directory.
      <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      Cythonizing sources
      Traceback (most recent call last):
        File "/Users/erioe/PycharmProjects/cloud-ability-orion/venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/erioe/PycharmProjects/cloud-ability-orion/venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/erioe/PycharmProjects/cloud-ability-orion/venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/v8/gk_4t45j1nsdpk0rkg56hbgw0000gn/T/pip-build-env-g0go6hb3/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/v8/gk_4t45j1nsdpk0rkg56hbgw0000gn/T/pip-build-env-g0go6hb3/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/v8/gk_4t45j1nsdpk0rkg56hbgw0000gn/T/pip-build-env-g0go6hb3/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 488, in <module>
        File "<string>", line 469, in setup_package
        File "<string>", line 275, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by sarahmish** [comment]
Hi @erioe-m, thank you for opening an issue

I tested the environment from my side and everything is working correctly. Can you try installing it in a new environment as to not clash with existing package versions?

**Comment by DataWizardary** [comment]
Hi Sarah, I am facing a similar issue while installing orion-ml in my Windows machine using pip install orion-ml. Please find the snapshot of the error obtained. I tried installing in two different Windows machines from PyCharm using a new virtual machine. But am getting the same error in both the cases. 

Could you please help with the same. 

Collecting mongoengine<0.17,>=0.16.3
  Downloading mongoengine-0.16.3.tar.gz (149 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.0/149.0 kB 4.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in mongoengine setup command: use_2to3 is invalid.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by DataWizardary** [comment]
Thanks Sarah. I downloaded to Python 3.8 and was able to install the package

**Comment by soyasis** [comment]
Hola @sarahmish , I'm creating a new conda env with Python 3.8.18 on MacOS 13.5.1, running `pip install orion-ml==0.5.1` and getting the same error as @erioe-m → any suggestions will be highly appreciated 😇

```(orion) ➜  fastapi-svg-parser git:(dev) ✗ pip install orion-ml==0.5.1     
Collecting orion-ml==0.5.1
  Obtaining dependency information for orion-ml==0.5.1 from https://files.pythonhosted.org/packages/38/38/103c115f0ffc488e52f3df4bd50f3f143f4902a966875f54e0b7a4ef3638/orion_ml-0.5.1-py2.py3-none-any.whl.metadata
  Using cached orion_ml-0.5.1-py2.py3-none-any.whl.metadata (23 kB)
Collecting s3fs<0.5,>=0.2.2 (from orion-ml==0.5.1)
  Using cached s3fs-0.4.2-py3-none-any.whl (19 kB)
Collecting mlblocks<0.5,>=0.4.1 (from orion-ml==0.5.1)
  Using cached mlblocks-0.4.1-py2.py3-none-any.whl (25 kB)
Collecting ml-stars<0.2,>=0.1.1 (from orion-ml==0.5.1)
  Obtaining dependency information for ml-stars<0.2,>=0.1.1 from https://files.pythonhosted.org/packages/fc/75/79c9b3f1bb5e5891c3a4541c14ae380a8fdce59245b2185bcda262d47ae0/ml_stars-0.1.3-py2.py3-none-any.whl.metadata
  Using cached ml_stars-0.1.3-py2.py3-none-any.whl.metadata (7.6 kB)
Collecting numpy<1.19,>=1.17.4 (from orion-ml==0.5.1)
  Using cached numpy-1.18.5.zip (5.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      warning: _philox.pyx:19:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: /private/var/folders/kc/hw29d49j3gg3dw2whdsr2cm40000gn/T/pip-install-fh_f0295/numpy_c9730c8441884b94b57032596bb7d0e1/numpy/__init__.pxd:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  self.rng_state.ctr.v[i] = counter[i]
      
              self._reset_state_variables()
      
              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &philox_uint64
                                         ^
      ------------------------------------------------------------
      
      _philox.pyx:195:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'uint64_t (void *) except? -1 nogil'.
      /private/var/folders/kc/hw29d49j3gg3dw2whdsr2cm40000gn/T/pip-install-fh_f0295/numpy_c9730c8441884b94b57032596bb7d0e1/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      /private/var/folders/kc/hw29d49j3gg3dw2whdsr2cm40000gn/T/pip-install-fh_f0295/numpy_c9730c8441884b94b57032596bb7d0e1/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_philox.pyx
      Traceback (most recent call last):
        File "/private/var/folders/kc/hw29d49j3gg3dw2whdsr2cm40000gn/T/pip-install-fh_f0295/numpy_c9730c8441884b94b57032596bb7d0e1/tools/cythonize.py", line 238, in <module>
          main()
        File "/private/var/folders/kc/hw29d49j3gg3dw2whdsr2cm40000gn/T/pip-install-fh_f0295/numpy_c9730c8441884b94b57032596bb7d0e1/tools/cythonize.py", line 234, in main
          find_process_files(root_dir)
        File "/private/var/folders/kc/hw29d49j3gg3dw2whdsr2cm40000gn/T/pip-install-fh_f0295/numpy_c9730c8441884b94b57032596bb7d0e1/tools/cythonize.py", line 225, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/private/var/folders/kc/hw29d49j3gg3dw2whdsr2cm40000gn/T/pip-install-fh_f0295/numpy_c9730c8441884b94b57032596bb7d0e1/tools/cythonize.py", line 191, in process
          processor_function(fromfile, tofile)
        File "/private/var/folders/kc/hw29d49j3gg3dw2whdsr2cm40000gn/T/pip-install-fh_f0295/numpy_c9730c8441884b94b57032596bb7d0e1/tools/cythonize.py", line 80, in process_pyx
          subprocess.check_call(
        File "/opt/homebrew/anaconda3/envs/orion/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/opt/homebrew/anaconda3/envs/orion/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_philox.c', '_philox.pyx']' returned non-zero exit status 1.
      Running from numpy source directory.
      <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      Cythonizing sources
      Traceback (most recent call last):
        File "/opt/homebrew/anaconda3/envs/orion/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/homebrew/anaconda3/envs/orion/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/homebrew/anaconda3/envs/orion/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/kc/hw29d49j3gg3dw2whdsr2cm40000gn/T/pip-build-env-mfpakfwz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/private/var/folders/kc/hw29d49j3gg3dw2whdsr2cm40000gn/T/pip-build-env-mfpakfwz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/kc/hw29d49j3gg3dw2whdsr2cm40000gn/T/pip-build-env-mfpakfwz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 488, in <module>
        File "<string>", line 469, in setup_package
        File "<string>", line 275, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.```
